/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CompetitorsCarDetails {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("price")
  private String price = null;
  @SerializedName("miles")
  private String miles = null;
  @SerializedName("avg_market_value")
  private String avgMarketValue = null;

  /**
   * Current car name
   **/
  @ApiModelProperty(value = "Current car name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * price of car
   **/
  @ApiModelProperty(value = "price of car")
  public String getPrice() {
    return price;
  }
  public void setPrice(String price) {
    this.price = price;
  }

  /**
   * mileage of car
   **/
  @ApiModelProperty(value = "mileage of car")
  public String getMiles() {
    return miles;
  }
  public void setMiles(String miles) {
    this.miles = miles;
  }

  /**
   * Estimated market value
   **/
  @ApiModelProperty(value = "Estimated market value")
  public String getAvgMarketValue() {
    return avgMarketValue;
  }
  public void setAvgMarketValue(String avgMarketValue) {
    this.avgMarketValue = avgMarketValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorsCarDetails competitorsCarDetails = (CompetitorsCarDetails) o;
    return (this.name == null ? competitorsCarDetails.name == null : this.name.equals(competitorsCarDetails.name)) &&
        (this.price == null ? competitorsCarDetails.price == null : this.price.equals(competitorsCarDetails.price)) &&
        (this.miles == null ? competitorsCarDetails.miles == null : this.miles.equals(competitorsCarDetails.miles)) &&
        (this.avgMarketValue == null ? competitorsCarDetails.avgMarketValue == null : this.avgMarketValue.equals(competitorsCarDetails.avgMarketValue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.miles == null ? 0: this.miles.hashCode());
    result = 31 * result + (this.avgMarketValue == null ? 0: this.avgMarketValue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorsCarDetails {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  miles: ").append(miles).append("\n");
    sb.append("  avgMarketValue: ").append(avgMarketValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
