/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CompetitorsSameCars {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("avg_price")
  private BigDecimal avgPrice = null;
  @SerializedName("avg_miles")
  private BigDecimal avgMiles = null;
  @SerializedName("avg_market_value")
  private BigDecimal avgMarketValue = null;

  /**
   * ymm_comb_name
   **/
  @ApiModelProperty(value = "ymm_comb_name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Price of year make model combination
   **/
  @ApiModelProperty(value = "Price of year make model combination")
  public BigDecimal getAvgPrice() {
    return avgPrice;
  }
  public void setAvgPrice(BigDecimal avgPrice) {
    this.avgPrice = avgPrice;
  }

  /**
   * Mileage of year make model combination
   **/
  @ApiModelProperty(value = "Mileage of year make model combination")
  public BigDecimal getAvgMiles() {
    return avgMiles;
  }
  public void setAvgMiles(BigDecimal avgMiles) {
    this.avgMiles = avgMiles;
  }

  /**
   * Estimated market value of year make model combination
   **/
  @ApiModelProperty(value = "Estimated market value of year make model combination")
  public BigDecimal getAvgMarketValue() {
    return avgMarketValue;
  }
  public void setAvgMarketValue(BigDecimal avgMarketValue) {
    this.avgMarketValue = avgMarketValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorsSameCars competitorsSameCars = (CompetitorsSameCars) o;
    return (this.name == null ? competitorsSameCars.name == null : this.name.equals(competitorsSameCars.name)) &&
        (this.avgPrice == null ? competitorsSameCars.avgPrice == null : this.avgPrice.equals(competitorsSameCars.avgPrice)) &&
        (this.avgMiles == null ? competitorsSameCars.avgMiles == null : this.avgMiles.equals(competitorsSameCars.avgMiles)) &&
        (this.avgMarketValue == null ? competitorsSameCars.avgMarketValue == null : this.avgMarketValue.equals(competitorsSameCars.avgMarketValue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.avgPrice == null ? 0: this.avgPrice.hashCode());
    result = 31 * result + (this.avgMiles == null ? 0: this.avgMiles.hashCode());
    result = 31 * result + (this.avgMarketValue == null ? 0: this.avgMarketValue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorsSameCars {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  avgPrice: ").append(avgPrice).append("\n");
    sb.append("  avgMiles: ").append(avgMiles).append("\n");
    sb.append("  avgMarketValue: ").append(avgMarketValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
