/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CompetitorsCarDetails;
import io.swagger.client.model.CompetitorsSameCars;
import io.swagger.client.model.CompetitorsSimilarCars;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CompetitorsPoint {
  
  @SerializedName("current_car")
  private CompetitorsCarDetails currentCar = null;
  @SerializedName("similar_car_models")
  private List<CompetitorsSimilarCars> similarCarModels = null;
  @SerializedName("same_car_models")
  private List<CompetitorsSameCars> sameCarModels = null;

  /**
   * Details of current car
   **/
  @ApiModelProperty(value = "Details of current car")
  public CompetitorsCarDetails getCurrentCar() {
    return currentCar;
  }
  public void setCurrentCar(CompetitorsCarDetails currentCar) {
    this.currentCar = currentCar;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CompetitorsSimilarCars> getSimilarCarModels() {
    return similarCarModels;
  }
  public void setSimilarCarModels(List<CompetitorsSimilarCars> similarCarModels) {
    this.similarCarModels = similarCarModels;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CompetitorsSameCars> getSameCarModels() {
    return sameCarModels;
  }
  public void setSameCarModels(List<CompetitorsSameCars> sameCarModels) {
    this.sameCarModels = sameCarModels;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorsPoint competitorsPoint = (CompetitorsPoint) o;
    return (this.currentCar == null ? competitorsPoint.currentCar == null : this.currentCar.equals(competitorsPoint.currentCar)) &&
        (this.similarCarModels == null ? competitorsPoint.similarCarModels == null : this.similarCarModels.equals(competitorsPoint.similarCarModels)) &&
        (this.sameCarModels == null ? competitorsPoint.sameCarModels == null : this.sameCarModels.equals(competitorsPoint.sameCarModels));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.currentCar == null ? 0: this.currentCar.hashCode());
    result = 31 * result + (this.similarCarModels == null ? 0: this.similarCarModels.hashCode());
    result = 31 * result + (this.sameCarModels == null ? 0: this.sameCarModels.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorsPoint {\n");
    
    sb.append("  currentCar: ").append(currentCar).append("\n");
    sb.append("  similarCarModels: ").append(similarCarModels).append("\n");
    sb.append("  sameCarModels: ").append(sameCarModels).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
