/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ComparisonPoint {
  
  @SerializedName("similar_vehicles_count")
  private BigDecimal similarVehiclesCount = null;
  @SerializedName("dealer_indicator")
  private String dealerIndicator = null;
  @SerializedName("vin_price")
  private BigDecimal vinPrice = null;
  @SerializedName("fair_deal_price")
  private BigDecimal fairDealPrice = null;

  /**
   * Similar Vehicles Count
   **/
  @ApiModelProperty(value = "Similar Vehicles Count")
  public BigDecimal getSimilarVehiclesCount() {
    return similarVehiclesCount;
  }
  public void setSimilarVehiclesCount(BigDecimal similarVehiclesCount) {
    this.similarVehiclesCount = similarVehiclesCount;
  }

  /**
   * Deal Indicator
   **/
  @ApiModelProperty(value = "Deal Indicator")
  public String getDealerIndicator() {
    return dealerIndicator;
  }
  public void setDealerIndicator(String dealerIndicator) {
    this.dealerIndicator = dealerIndicator;
  }

  /**
   * Price for Vin
   **/
  @ApiModelProperty(value = "Price for Vin")
  public BigDecimal getVinPrice() {
    return vinPrice;
  }
  public void setVinPrice(BigDecimal vinPrice) {
    this.vinPrice = vinPrice;
  }

  /**
   * Fair Deal Price
   **/
  @ApiModelProperty(value = "Fair Deal Price")
  public BigDecimal getFairDealPrice() {
    return fairDealPrice;
  }
  public void setFairDealPrice(BigDecimal fairDealPrice) {
    this.fairDealPrice = fairDealPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComparisonPoint comparisonPoint = (ComparisonPoint) o;
    return (this.similarVehiclesCount == null ? comparisonPoint.similarVehiclesCount == null : this.similarVehiclesCount.equals(comparisonPoint.similarVehiclesCount)) &&
        (this.dealerIndicator == null ? comparisonPoint.dealerIndicator == null : this.dealerIndicator.equals(comparisonPoint.dealerIndicator)) &&
        (this.vinPrice == null ? comparisonPoint.vinPrice == null : this.vinPrice.equals(comparisonPoint.vinPrice)) &&
        (this.fairDealPrice == null ? comparisonPoint.fairDealPrice == null : this.fairDealPrice.equals(comparisonPoint.fairDealPrice));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.similarVehiclesCount == null ? 0: this.similarVehiclesCount.hashCode());
    result = 31 * result + (this.dealerIndicator == null ? 0: this.dealerIndicator.hashCode());
    result = 31 * result + (this.vinPrice == null ? 0: this.vinPrice.hashCode());
    result = 31 * result + (this.fairDealPrice == null ? 0: this.fairDealPrice.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComparisonPoint {\n");
    
    sb.append("  similarVehiclesCount: ").append(similarVehiclesCount).append("\n");
    sb.append("  dealerIndicator: ").append(dealerIndicator).append("\n");
    sb.append("  vinPrice: ").append(vinPrice).append("\n");
    sb.append("  fairDealPrice: ").append(fairDealPrice).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
