/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.RatingComponents;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DealerRating {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("zip")
  private String zip = null;
  @SerializedName("latitude")
  private String latitude = null;
  @SerializedName("longitude")
  private String longitude = null;
  @SerializedName("overall_rating")
  private BigDecimal overallRating = null;
  @SerializedName("rating_components")
  private List<RatingComponents> ratingComponents = null;

  /**
   * Name of the dealer
   **/
  @ApiModelProperty(value = "Name of the dealer")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Street of the dealer
   **/
  @ApiModelProperty(value = "Street of the dealer")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   * City of the dealer
   **/
  @ApiModelProperty(value = "City of the dealer")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * State of the dealer
   **/
  @ApiModelProperty(value = "State of the dealer")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   * Zip of the dealer
   **/
  @ApiModelProperty(value = "Zip of the dealer")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }

  /**
   * Latutide for the dealer location
   **/
  @ApiModelProperty(value = "Latutide for the dealer location")
  public String getLatitude() {
    return latitude;
  }
  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  /**
   * Longitude for the dealer location
   **/
  @ApiModelProperty(value = "Longitude for the dealer location")
  public String getLongitude() {
    return longitude;
  }
  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  /**
   * Overall rating of the dealership on scale 1-5
   **/
  @ApiModelProperty(value = "Overall rating of the dealership on scale 1-5")
  public BigDecimal getOverallRating() {
    return overallRating;
  }
  public void setOverallRating(BigDecimal overallRating) {
    this.overallRating = overallRating;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<RatingComponents> getRatingComponents() {
    return ratingComponents;
  }
  public void setRatingComponents(List<RatingComponents> ratingComponents) {
    this.ratingComponents = ratingComponents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealerRating dealerRating = (DealerRating) o;
    return (this.name == null ? dealerRating.name == null : this.name.equals(dealerRating.name)) &&
        (this.street == null ? dealerRating.street == null : this.street.equals(dealerRating.street)) &&
        (this.city == null ? dealerRating.city == null : this.city.equals(dealerRating.city)) &&
        (this.state == null ? dealerRating.state == null : this.state.equals(dealerRating.state)) &&
        (this.zip == null ? dealerRating.zip == null : this.zip.equals(dealerRating.zip)) &&
        (this.latitude == null ? dealerRating.latitude == null : this.latitude.equals(dealerRating.latitude)) &&
        (this.longitude == null ? dealerRating.longitude == null : this.longitude.equals(dealerRating.longitude)) &&
        (this.overallRating == null ? dealerRating.overallRating == null : this.overallRating.equals(dealerRating.overallRating)) &&
        (this.ratingComponents == null ? dealerRating.ratingComponents == null : this.ratingComponents.equals(dealerRating.ratingComponents));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    result = 31 * result + (this.overallRating == null ? 0: this.overallRating.hashCode());
    result = 31 * result + (this.ratingComponents == null ? 0: this.ratingComponents.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealerRating {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("  overallRating: ").append(overallRating).append("\n");
    sb.append("  ratingComponents: ").append(ratingComponents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
