/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Dealer {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("franchise_id")
  private String franchiseId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("city")
  private String city = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("zip")
  private String zip = null;
  @SerializedName("latitude")
  private String latitude = null;
  @SerializedName("longitude")
  private String longitude = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("car_type")
  private String carType = null;
  @SerializedName("target_url_new")
  private String targetUrlNew = null;
  @SerializedName("target_url_used")
  private String targetUrlUsed = null;
  @SerializedName("target_url_certified")
  private String targetUrlCertified = null;
  @SerializedName("dealer_type")
  private String dealerType = null;
  @SerializedName("rating")
  private BigDecimal rating = null;

  /**
   * The unique id associated with the dealer in the Marketcheck database
   **/
  @ApiModelProperty(value = "The unique id associated with the dealer in the Marketcheck database")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Dealer franchise id
   **/
  @ApiModelProperty(value = "Dealer franchise id")
  public String getFranchiseId() {
    return franchiseId;
  }
  public void setFranchiseId(String franchiseId) {
    this.franchiseId = franchiseId;
  }

  /**
   * Name of the dealer
   **/
  @ApiModelProperty(value = "Name of the dealer")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Street of the dealer
   **/
  @ApiModelProperty(value = "Street of the dealer")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   * City of the dealer
   **/
  @ApiModelProperty(value = "City of the dealer")
  public String getCity() {
    return city;
  }
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * State of the dealer
   **/
  @ApiModelProperty(value = "State of the dealer")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   * Zip of the dealer
   **/
  @ApiModelProperty(value = "Zip of the dealer")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }

  /**
   * Latutide for the dealer location
   **/
  @ApiModelProperty(value = "Latutide for the dealer location")
  public String getLatitude() {
    return latitude;
  }
  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  /**
   * Longitude for the dealer location
   **/
  @ApiModelProperty(value = "Longitude for the dealer location")
  public String getLongitude() {
    return longitude;
  }
  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  /**
   * Contact no of the dealer
   **/
  @ApiModelProperty(value = "Contact no of the dealer")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * Car type new|used|certified
   **/
  @ApiModelProperty(value = "Car type new|used|certified")
  public String getCarType() {
    return carType;
  }
  public void setCarType(String carType) {
    this.carType = carType;
  }

  /**
   * Target url for the new cars listing
   **/
  @ApiModelProperty(value = "Target url for the new cars listing")
  public String getTargetUrlNew() {
    return targetUrlNew;
  }
  public void setTargetUrlNew(String targetUrlNew) {
    this.targetUrlNew = targetUrlNew;
  }

  /**
   * Target url for the used cars listing
   **/
  @ApiModelProperty(value = "Target url for the used cars listing")
  public String getTargetUrlUsed() {
    return targetUrlUsed;
  }
  public void setTargetUrlUsed(String targetUrlUsed) {
    this.targetUrlUsed = targetUrlUsed;
  }

  /**
   * Target url for the certified cars listing
   **/
  @ApiModelProperty(value = "Target url for the certified cars listing")
  public String getTargetUrlCertified() {
    return targetUrlCertified;
  }
  public void setTargetUrlCertified(String targetUrlCertified) {
    this.targetUrlCertified = targetUrlCertified;
  }

  /**
   * Dealer type - independent, franchise, multi-brand, authorized
   **/
  @ApiModelProperty(value = "Dealer type - independent, franchise, multi-brand, authorized")
  public String getDealerType() {
    return dealerType;
  }
  public void setDealerType(String dealerType) {
    this.dealerType = dealerType;
  }

  /**
   * Overall rating of the dealership on scale 1-5
   **/
  @ApiModelProperty(value = "Overall rating of the dealership on scale 1-5")
  public BigDecimal getRating() {
    return rating;
  }
  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dealer dealer = (Dealer) o;
    return (this.id == null ? dealer.id == null : this.id.equals(dealer.id)) &&
        (this.franchiseId == null ? dealer.franchiseId == null : this.franchiseId.equals(dealer.franchiseId)) &&
        (this.name == null ? dealer.name == null : this.name.equals(dealer.name)) &&
        (this.street == null ? dealer.street == null : this.street.equals(dealer.street)) &&
        (this.city == null ? dealer.city == null : this.city.equals(dealer.city)) &&
        (this.state == null ? dealer.state == null : this.state.equals(dealer.state)) &&
        (this.zip == null ? dealer.zip == null : this.zip.equals(dealer.zip)) &&
        (this.latitude == null ? dealer.latitude == null : this.latitude.equals(dealer.latitude)) &&
        (this.longitude == null ? dealer.longitude == null : this.longitude.equals(dealer.longitude)) &&
        (this.phone == null ? dealer.phone == null : this.phone.equals(dealer.phone)) &&
        (this.carType == null ? dealer.carType == null : this.carType.equals(dealer.carType)) &&
        (this.targetUrlNew == null ? dealer.targetUrlNew == null : this.targetUrlNew.equals(dealer.targetUrlNew)) &&
        (this.targetUrlUsed == null ? dealer.targetUrlUsed == null : this.targetUrlUsed.equals(dealer.targetUrlUsed)) &&
        (this.targetUrlCertified == null ? dealer.targetUrlCertified == null : this.targetUrlCertified.equals(dealer.targetUrlCertified)) &&
        (this.dealerType == null ? dealer.dealerType == null : this.dealerType.equals(dealer.dealerType)) &&
        (this.rating == null ? dealer.rating == null : this.rating.equals(dealer.rating));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.franchiseId == null ? 0: this.franchiseId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.city == null ? 0: this.city.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.carType == null ? 0: this.carType.hashCode());
    result = 31 * result + (this.targetUrlNew == null ? 0: this.targetUrlNew.hashCode());
    result = 31 * result + (this.targetUrlUsed == null ? 0: this.targetUrlUsed.hashCode());
    result = 31 * result + (this.targetUrlCertified == null ? 0: this.targetUrlCertified.hashCode());
    result = 31 * result + (this.dealerType == null ? 0: this.dealerType.hashCode());
    result = 31 * result + (this.rating == null ? 0: this.rating.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dealer {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  franchiseId: ").append(franchiseId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  city: ").append(city).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  carType: ").append(carType).append("\n");
    sb.append("  targetUrlNew: ").append(targetUrlNew).append("\n");
    sb.append("  targetUrlUsed: ").append(targetUrlUsed).append("\n");
    sb.append("  targetUrlCertified: ").append(targetUrlCertified).append("\n");
    sb.append("  dealerType: ").append(dealerType).append("\n");
    sb.append("  rating: ").append(rating).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
