/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Economy {
  
  @SerializedName("ghg_emissions_rating")
  private BigDecimal ghgEmissionsRating = null;
  @SerializedName("ghg_emissions_indicator")
  private String ghgEmissionsIndicator = null;
  @SerializedName("smog_rating")
  private BigDecimal smogRating = null;
  @SerializedName("smog_indicator")
  private String smogIndicator = null;

  /**
   * Show vehicle impact on climate change in terms of greeenhouse gases. This rating will be in the range of 1 - 10
   **/
  @ApiModelProperty(value = "Show vehicle impact on climate change in terms of greeenhouse gases. This rating will be in the range of 1 - 10")
  public BigDecimal getGhgEmissionsRating() {
    return ghgEmissionsRating;
  }
  public void setGhgEmissionsRating(BigDecimal ghgEmissionsRating) {
    this.ghgEmissionsRating = ghgEmissionsRating;
  }

  /**
   * Contains text like bad|Good|Very Good| Excellent
   **/
  @ApiModelProperty(value = "Contains text like bad|Good|Very Good| Excellent")
  public String getGhgEmissionsIndicator() {
    return ghgEmissionsIndicator;
  }
  public void setGhgEmissionsIndicator(String ghgEmissionsIndicator) {
    this.ghgEmissionsIndicator = ghgEmissionsIndicator;
  }

  /**
   * Shows vehicle's emissions of pollutants known to cause smog and other forms of air pollution. This rating will be in the range of 1 - 10
   **/
  @ApiModelProperty(value = "Shows vehicle's emissions of pollutants known to cause smog and other forms of air pollution. This rating will be in the range of 1 - 10")
  public BigDecimal getSmogRating() {
    return smogRating;
  }
  public void setSmogRating(BigDecimal smogRating) {
    this.smogRating = smogRating;
  }

  /**
   * Contains text like bad|Good|Very Good| Excellent
   **/
  @ApiModelProperty(value = "Contains text like bad|Good|Very Good| Excellent")
  public String getSmogIndicator() {
    return smogIndicator;
  }
  public void setSmogIndicator(String smogIndicator) {
    this.smogIndicator = smogIndicator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Economy economy = (Economy) o;
    return (this.ghgEmissionsRating == null ? economy.ghgEmissionsRating == null : this.ghgEmissionsRating.equals(economy.ghgEmissionsRating)) &&
        (this.ghgEmissionsIndicator == null ? economy.ghgEmissionsIndicator == null : this.ghgEmissionsIndicator.equals(economy.ghgEmissionsIndicator)) &&
        (this.smogRating == null ? economy.smogRating == null : this.smogRating.equals(economy.smogRating)) &&
        (this.smogIndicator == null ? economy.smogIndicator == null : this.smogIndicator.equals(economy.smogIndicator));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ghgEmissionsRating == null ? 0: this.ghgEmissionsRating.hashCode());
    result = 31 * result + (this.ghgEmissionsIndicator == null ? 0: this.ghgEmissionsIndicator.hashCode());
    result = 31 * result + (this.smogRating == null ? 0: this.smogRating.hashCode());
    result = 31 * result + (this.smogIndicator == null ? 0: this.smogIndicator.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Economy {\n");
    
    sb.append("  ghgEmissionsRating: ").append(ghgEmissionsRating).append("\n");
    sb.append("  ghgEmissionsIndicator: ").append(ghgEmissionsIndicator).append("\n");
    sb.append("  smogRating: ").append(smogRating).append("\n");
    sb.append("  smogIndicator: ").append(smogIndicator).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
