/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListingDebugAttributes {
  
  @SerializedName("robot_id")
  private BigDecimal robotId = null;
  @SerializedName("cycle_id")
  private BigDecimal cycleId = null;
  @SerializedName("scraped_at")
  private String scrapedAt = null;
  @SerializedName("template_id")
  private BigDecimal templateId = null;
  @SerializedName("user_id")
  private BigDecimal userId = null;
  @SerializedName("taxonomy_vin")
  private String taxonomyVin = null;

  /**
   * Robot id
   **/
  @ApiModelProperty(value = "Robot id")
  public BigDecimal getRobotId() {
    return robotId;
  }
  public void setRobotId(BigDecimal robotId) {
    this.robotId = robotId;
  }

  /**
   * Cycle id
   **/
  @ApiModelProperty(value = "Cycle id")
  public BigDecimal getCycleId() {
    return cycleId;
  }
  public void setCycleId(BigDecimal cycleId) {
    this.cycleId = cycleId;
  }

  /**
   * Scraped date and time
   **/
  @ApiModelProperty(value = "Scraped date and time")
  public String getScrapedAt() {
    return scrapedAt;
  }
  public void setScrapedAt(String scrapedAt) {
    this.scrapedAt = scrapedAt;
  }

  /**
   * Template id
   **/
  @ApiModelProperty(value = "Template id")
  public BigDecimal getTemplateId() {
    return templateId;
  }
  public void setTemplateId(BigDecimal templateId) {
    this.templateId = templateId;
  }

  /**
   * User id
   **/
  @ApiModelProperty(value = "User id")
  public BigDecimal getUserId() {
    return userId;
  }
  public void setUserId(BigDecimal userId) {
    this.userId = userId;
  }

  /**
   * Taxonomy vin
   **/
  @ApiModelProperty(value = "Taxonomy vin")
  public String getTaxonomyVin() {
    return taxonomyVin;
  }
  public void setTaxonomyVin(String taxonomyVin) {
    this.taxonomyVin = taxonomyVin;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingDebugAttributes listingDebugAttributes = (ListingDebugAttributes) o;
    return (this.robotId == null ? listingDebugAttributes.robotId == null : this.robotId.equals(listingDebugAttributes.robotId)) &&
        (this.cycleId == null ? listingDebugAttributes.cycleId == null : this.cycleId.equals(listingDebugAttributes.cycleId)) &&
        (this.scrapedAt == null ? listingDebugAttributes.scrapedAt == null : this.scrapedAt.equals(listingDebugAttributes.scrapedAt)) &&
        (this.templateId == null ? listingDebugAttributes.templateId == null : this.templateId.equals(listingDebugAttributes.templateId)) &&
        (this.userId == null ? listingDebugAttributes.userId == null : this.userId.equals(listingDebugAttributes.userId)) &&
        (this.taxonomyVin == null ? listingDebugAttributes.taxonomyVin == null : this.taxonomyVin.equals(listingDebugAttributes.taxonomyVin));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.robotId == null ? 0: this.robotId.hashCode());
    result = 31 * result + (this.cycleId == null ? 0: this.cycleId.hashCode());
    result = 31 * result + (this.scrapedAt == null ? 0: this.scrapedAt.hashCode());
    result = 31 * result + (this.templateId == null ? 0: this.templateId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.taxonomyVin == null ? 0: this.taxonomyVin.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingDebugAttributes {\n");
    
    sb.append("  robotId: ").append(robotId).append("\n");
    sb.append("  cycleId: ").append(cycleId).append("\n");
    sb.append("  scrapedAt: ").append(scrapedAt).append("\n");
    sb.append("  templateId: ").append(templateId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  taxonomyVin: ").append(taxonomyVin).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
