/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ListingMedia {
  
  @SerializedName("photo_link")
  private String photoLink = null;
  @SerializedName("photo_links")
  private List<String> photoLinks = null;

  /**
   * Single photo url of the car
   **/
  @ApiModelProperty(value = "Single photo url of the car")
  public String getPhotoLink() {
    return photoLink;
  }
  public void setPhotoLink(String photoLink) {
    this.photoLink = photoLink;
  }

  /**
   * A list of photo urls for the car
   **/
  @ApiModelProperty(value = "A list of photo urls for the car")
  public List<String> getPhotoLinks() {
    return photoLinks;
  }
  public void setPhotoLinks(List<String> photoLinks) {
    this.photoLinks = photoLinks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingMedia listingMedia = (ListingMedia) o;
    return (this.photoLink == null ? listingMedia.photoLink == null : this.photoLink.equals(listingMedia.photoLink)) &&
        (this.photoLinks == null ? listingMedia.photoLinks == null : this.photoLinks.equals(listingMedia.photoLinks));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.photoLink == null ? 0: this.photoLink.hashCode());
    result = 31 * result + (this.photoLinks == null ? 0: this.photoLinks.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingMedia {\n");
    
    sb.append("  photoLink: ").append(photoLink).append("\n");
    sb.append("  photoLinks: ").append(photoLinks).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
