/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Describes Market days supply results for year make model trim combination
 **/
@ApiModel(description = "Describes Market days supply results for year make model trim combination")
public class Mds {
  
  @SerializedName("mds")
  private BigDecimal mds = null;
  @SerializedName("total_active_cars_for_ymmt")
  private BigDecimal totalActiveCarsForYmmt = null;
  @SerializedName("total_cars_sold_in_last_45_days")
  private BigDecimal totalCarsSoldInLast45Days = null;

  /**
   * Provides Market days supply count
   **/
  @ApiModelProperty(value = "Provides Market days supply count")
  public BigDecimal getMds() {
    return mds;
  }
  public void setMds(BigDecimal mds) {
    this.mds = mds;
  }

  /**
   * Active cars for ymmt combination
   **/
  @ApiModelProperty(value = "Active cars for ymmt combination")
  public BigDecimal getTotalActiveCarsForYmmt() {
    return totalActiveCarsForYmmt;
  }
  public void setTotalActiveCarsForYmmt(BigDecimal totalActiveCarsForYmmt) {
    this.totalActiveCarsForYmmt = totalActiveCarsForYmmt;
  }

  /**
   * Cars sold in last 45 days
   **/
  @ApiModelProperty(value = "Cars sold in last 45 days")
  public BigDecimal getTotalCarsSoldInLast45Days() {
    return totalCarsSoldInLast45Days;
  }
  public void setTotalCarsSoldInLast45Days(BigDecimal totalCarsSoldInLast45Days) {
    this.totalCarsSoldInLast45Days = totalCarsSoldInLast45Days;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mds mds = (Mds) o;
    return (this.mds == null ? mds.mds == null : this.mds.equals(mds.mds)) &&
        (this.totalActiveCarsForYmmt == null ? mds.totalActiveCarsForYmmt == null : this.totalActiveCarsForYmmt.equals(mds.totalActiveCarsForYmmt)) &&
        (this.totalCarsSoldInLast45Days == null ? mds.totalCarsSoldInLast45Days == null : this.totalCarsSoldInLast45Days.equals(mds.totalCarsSoldInLast45Days));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mds == null ? 0: this.mds.hashCode());
    result = 31 * result + (this.totalActiveCarsForYmmt == null ? 0: this.totalActiveCarsForYmmt.hashCode());
    result = 31 * result + (this.totalCarsSoldInLast45Days == null ? 0: this.totalCarsSoldInLast45Days.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mds {\n");
    
    sb.append("  mds: ").append(mds).append("\n");
    sb.append("  totalActiveCarsForYmmt: ").append(totalActiveCarsForYmmt).append("\n");
    sb.append("  totalCarsSoldInLast45Days: ").append(totalCarsSoldInLast45Days).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
