/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RatingComponents {
  
  @SerializedName("rating_condition")
  private String ratingCondition = null;
  @SerializedName("actual_rating")
  private BigDecimal actualRating = null;

  /**
   * Specifices rating condition parameter
   **/
  @ApiModelProperty(value = "Specifices rating condition parameter")
  public String getRatingCondition() {
    return ratingCondition;
  }
  public void setRatingCondition(String ratingCondition) {
    this.ratingCondition = ratingCondition;
  }

  /**
   * rating of car on that condition
   **/
  @ApiModelProperty(value = "rating of car on that condition")
  public BigDecimal getActualRating() {
    return actualRating;
  }
  public void setActualRating(BigDecimal actualRating) {
    this.actualRating = actualRating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingComponents ratingComponents = (RatingComponents) o;
    return (this.ratingCondition == null ? ratingComponents.ratingCondition == null : this.ratingCondition.equals(ratingComponents.ratingCondition)) &&
        (this.actualRating == null ? ratingComponents.actualRating == null : this.actualRating.equals(ratingComponents.actualRating));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ratingCondition == null ? 0: this.ratingCondition.hashCode());
    result = 31 * result + (this.actualRating == null ? 0: this.actualRating.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingComponents {\n");
    
    sb.append("  ratingCondition: ").append(ratingCondition).append("\n");
    sb.append("  actualRating: ").append(actualRating).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
