/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReviewComponents {
  
  @SerializedName("user_name")
  private String userName = null;
  @SerializedName("user_rating")
  private BigDecimal userRating = null;
  @SerializedName("actual_review")
  private String actualReview = null;

  /**
   * Name of user who has given review
   **/
  @ApiModelProperty(value = "Name of user who has given review")
  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * rating for dealer given by user ranging from 1-5
   **/
  @ApiModelProperty(value = "rating for dealer given by user ranging from 1-5")
  public BigDecimal getUserRating() {
    return userRating;
  }
  public void setUserRating(BigDecimal userRating) {
    this.userRating = userRating;
  }

  /**
   * review of car given by current user
   **/
  @ApiModelProperty(value = "review of car given by current user")
  public String getActualReview() {
    return actualReview;
  }
  public void setActualReview(String actualReview) {
    this.actualReview = actualReview;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewComponents reviewComponents = (ReviewComponents) o;
    return (this.userName == null ? reviewComponents.userName == null : this.userName.equals(reviewComponents.userName)) &&
        (this.userRating == null ? reviewComponents.userRating == null : this.userRating.equals(reviewComponents.userRating)) &&
        (this.actualReview == null ? reviewComponents.actualReview == null : this.actualReview.equals(reviewComponents.actualReview));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userName == null ? 0: this.userName.hashCode());
    result = 31 * result + (this.userRating == null ? 0: this.userRating.hashCode());
    result = 31 * result + (this.actualReview == null ? 0: this.actualReview.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewComponents {\n");
    
    sb.append("  userName: ").append(userName).append("\n");
    sb.append("  userRating: ").append(userRating).append("\n");
    sb.append("  actualReview: ").append(actualReview).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
