/**
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Describes the Safety Ratings of current listing
 **/
@ApiModel(description = "Describes the Safety Ratings of current listing")
public class SafetyRating {
  
  @SerializedName("overall_rating")
  private BigDecimal overallRating = null;
  @SerializedName("roll_over_rating")
  private BigDecimal rollOverRating = null;
  @SerializedName("driver_side_rating")
  private BigDecimal driverSideRating = null;
  @SerializedName("driver_front_rating")
  private BigDecimal driverFrontRating = null;
  @SerializedName("passenger_front_rating")
  private BigDecimal passengerFrontRating = null;

  /**
   * Overall rating of the Listing on scale 1-5
   **/
  @ApiModelProperty(value = "Overall rating of the Listing on scale 1-5")
  public BigDecimal getOverallRating() {
    return overallRating;
  }
  public void setOverallRating(BigDecimal overallRating) {
    this.overallRating = overallRating;
  }

  /**
   * Roll Over rating of the Listing on scale 1-5
   **/
  @ApiModelProperty(value = "Roll Over rating of the Listing on scale 1-5")
  public BigDecimal getRollOverRating() {
    return rollOverRating;
  }
  public void setRollOverRating(BigDecimal rollOverRating) {
    this.rollOverRating = rollOverRating;
  }

  /**
   * Driver Side rating of the Listing on scale 1-5
   **/
  @ApiModelProperty(value = "Driver Side rating of the Listing on scale 1-5")
  public BigDecimal getDriverSideRating() {
    return driverSideRating;
  }
  public void setDriverSideRating(BigDecimal driverSideRating) {
    this.driverSideRating = driverSideRating;
  }

  /**
   * Driver front rating of the Listing on scale 1-5
   **/
  @ApiModelProperty(value = "Driver front rating of the Listing on scale 1-5")
  public BigDecimal getDriverFrontRating() {
    return driverFrontRating;
  }
  public void setDriverFrontRating(BigDecimal driverFrontRating) {
    this.driverFrontRating = driverFrontRating;
  }

  /**
   * Passenger front rating of the Listing on scale 1-5
   **/
  @ApiModelProperty(value = "Passenger front rating of the Listing on scale 1-5")
  public BigDecimal getPassengerFrontRating() {
    return passengerFrontRating;
  }
  public void setPassengerFrontRating(BigDecimal passengerFrontRating) {
    this.passengerFrontRating = passengerFrontRating;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SafetyRating safetyRating = (SafetyRating) o;
    return (this.overallRating == null ? safetyRating.overallRating == null : this.overallRating.equals(safetyRating.overallRating)) &&
        (this.rollOverRating == null ? safetyRating.rollOverRating == null : this.rollOverRating.equals(safetyRating.rollOverRating)) &&
        (this.driverSideRating == null ? safetyRating.driverSideRating == null : this.driverSideRating.equals(safetyRating.driverSideRating)) &&
        (this.driverFrontRating == null ? safetyRating.driverFrontRating == null : this.driverFrontRating.equals(safetyRating.driverFrontRating)) &&
        (this.passengerFrontRating == null ? safetyRating.passengerFrontRating == null : this.passengerFrontRating.equals(safetyRating.passengerFrontRating));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.overallRating == null ? 0: this.overallRating.hashCode());
    result = 31 * result + (this.rollOverRating == null ? 0: this.rollOverRating.hashCode());
    result = 31 * result + (this.driverSideRating == null ? 0: this.driverSideRating.hashCode());
    result = 31 * result + (this.driverFrontRating == null ? 0: this.driverFrontRating.hashCode());
    result = 31 * result + (this.passengerFrontRating == null ? 0: this.passengerFrontRating.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SafetyRating {\n");
    
    sb.append("  overallRating: ").append(overallRating).append("\n");
    sb.append("  rollOverRating: ").append(rollOverRating).append("\n");
    sb.append("  driverSideRating: ").append(driverSideRating).append("\n");
    sb.append("  driverFrontRating: ").append(driverFrontRating).append("\n");
    sb.append("  passengerFrontRating: ").append(passengerFrontRating).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
